# /* (C) Copyright Paul Mensonides 2003 */
#
# ifndef CHAOS_PREPROCESSOR_STRINGIZE_HPP
# define CHAOS_PREPROCESSOR_STRINGIZE_HPP
#
# include <chaos/preprocessor/config.hpp>
# include <chaos/preprocessor/lambda/ops.hpp>
#
# /* CHAOS_PP_STRINGIZE */
#
# if CHAOS_PP_VARIADICS
#    define CHAOS_PP_STRINGIZE(...) CHAOS_PP_PRIMITIVE_STRINGIZE(__VA_ARGS__)
#    define CHAOS_PP_STRINGIZE_ CHAOS_PP_LAMBDA(CHAOS_PP_STRINGIZE)
# else
#    define CHAOS_PP_STRINGIZE(x) CHAOS_PP_PRIMITIVE_STRINGIZE(x)
# endif
#
# define CHAOS_PP_STRINGIZE_ID() CHAOS_PP_STRINGIZE
#
# /* CHAOS_PP_PRIMITIVE_STRINGIZE */
#
# if CHAOS_PP_VARIADICS
#    define CHAOS_PP_PRIMITIVE_STRINGIZE(...) #__VA_ARGS__
#    define CHAOS_PP_PRIMITIVE_STRINGIZE_ CHAOS_PP_LAMBDA(CHAOS_PP_PRIMITIVE_STRINGIZE)
# else
#    define CHAOS_PP_PRIMITIVE_STRINGIZE(x) #x
# endif
#
# define CHAOS_PP_PRIMITIVE_STRINGIZE_ID() CHAOS_PP_PRIMITIVE_STRINGIZE
#
# endif
