# /* *************************************************************************
#  *                                                                         *
#  *    (C) Copyright Paul Mensonides 2004.                                  *
#  *                                                                         *
#  *    Use, modification, and distribution are subject to Version 1.0 of    *
#  *    the Boost Software License.  (See accompanying file LICENSE.)        *
#  *                                                                         *
#  *    See http://chaos-pp.sourceforge.net for most recent version.         *
#  *                                                                         *
#  ************************************************************************* */
#
# include CHAOS_PP_SLOT_SHARED()
#
# undef CHAOS_IP_SLOT_1
#
# undef CHAOS_IP_SLOT_1_DIGIT_0
# undef CHAOS_IP_SLOT_1_DIGIT_1
# undef CHAOS_IP_SLOT_1_DIGIT_2
# undef CHAOS_IP_SLOT_1_DIGIT_3
# undef CHAOS_IP_SLOT_1_DIGIT_4
# undef CHAOS_IP_SLOT_1_DIGIT_5
# undef CHAOS_IP_SLOT_1_DIGIT_6
# undef CHAOS_IP_SLOT_1_DIGIT_7
# undef CHAOS_IP_SLOT_1_DIGIT_8
# undef CHAOS_IP_SLOT_1_DIGIT_9
#
# if CHAOS_IP_SLOT_TEMP_9 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_9 0
# elif CHAOS_IP_SLOT_TEMP_9 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_9 1
# elif CHAOS_IP_SLOT_TEMP_9 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_9 2
# elif CHAOS_IP_SLOT_TEMP_9 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_9 3
# elif CHAOS_IP_SLOT_TEMP_9 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_9 4
# elif CHAOS_IP_SLOT_TEMP_9 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_9 5
# elif CHAOS_IP_SLOT_TEMP_9 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_9 6
# elif CHAOS_IP_SLOT_TEMP_9 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_9 7
# elif CHAOS_IP_SLOT_TEMP_9 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_9 8
# elif CHAOS_IP_SLOT_TEMP_9 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_9 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_8 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_8 0
# elif CHAOS_IP_SLOT_TEMP_8 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_8 1
# elif CHAOS_IP_SLOT_TEMP_8 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_8 2
# elif CHAOS_IP_SLOT_TEMP_8 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_8 3
# elif CHAOS_IP_SLOT_TEMP_8 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_8 4
# elif CHAOS_IP_SLOT_TEMP_8 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_8 5
# elif CHAOS_IP_SLOT_TEMP_8 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_8 6
# elif CHAOS_IP_SLOT_TEMP_8 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_8 7
# elif CHAOS_IP_SLOT_TEMP_8 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_8 8
# elif CHAOS_IP_SLOT_TEMP_8 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_8 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_7 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_7 0
# elif CHAOS_IP_SLOT_TEMP_7 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_7 1
# elif CHAOS_IP_SLOT_TEMP_7 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_7 2
# elif CHAOS_IP_SLOT_TEMP_7 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_7 3
# elif CHAOS_IP_SLOT_TEMP_7 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_7 4
# elif CHAOS_IP_SLOT_TEMP_7 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_7 5
# elif CHAOS_IP_SLOT_TEMP_7 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_7 6
# elif CHAOS_IP_SLOT_TEMP_7 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_7 7
# elif CHAOS_IP_SLOT_TEMP_7 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_7 8
# elif CHAOS_IP_SLOT_TEMP_7 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_7 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_6 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_6 0
# elif CHAOS_IP_SLOT_TEMP_6 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_6 1
# elif CHAOS_IP_SLOT_TEMP_6 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_6 2
# elif CHAOS_IP_SLOT_TEMP_6 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_6 3
# elif CHAOS_IP_SLOT_TEMP_6 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_6 4
# elif CHAOS_IP_SLOT_TEMP_6 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_6 5
# elif CHAOS_IP_SLOT_TEMP_6 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_6 6
# elif CHAOS_IP_SLOT_TEMP_6 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_6 7
# elif CHAOS_IP_SLOT_TEMP_6 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_6 8
# elif CHAOS_IP_SLOT_TEMP_6 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_6 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_5 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_5 0
# elif CHAOS_IP_SLOT_TEMP_5 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_5 1
# elif CHAOS_IP_SLOT_TEMP_5 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_5 2
# elif CHAOS_IP_SLOT_TEMP_5 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_5 3
# elif CHAOS_IP_SLOT_TEMP_5 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_5 4
# elif CHAOS_IP_SLOT_TEMP_5 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_5 5
# elif CHAOS_IP_SLOT_TEMP_5 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_5 6
# elif CHAOS_IP_SLOT_TEMP_5 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_5 7
# elif CHAOS_IP_SLOT_TEMP_5 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_5 8
# elif CHAOS_IP_SLOT_TEMP_5 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_5 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_4 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_4 0
# elif CHAOS_IP_SLOT_TEMP_4 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_4 1
# elif CHAOS_IP_SLOT_TEMP_4 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_4 2
# elif CHAOS_IP_SLOT_TEMP_4 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_4 3
# elif CHAOS_IP_SLOT_TEMP_4 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_4 4
# elif CHAOS_IP_SLOT_TEMP_4 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_4 5
# elif CHAOS_IP_SLOT_TEMP_4 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_4 6
# elif CHAOS_IP_SLOT_TEMP_4 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_4 7
# elif CHAOS_IP_SLOT_TEMP_4 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_4 8
# elif CHAOS_IP_SLOT_TEMP_4 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_4 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_3 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_3 0
# elif CHAOS_IP_SLOT_TEMP_3 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_3 1
# elif CHAOS_IP_SLOT_TEMP_3 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_3 2
# elif CHAOS_IP_SLOT_TEMP_3 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_3 3
# elif CHAOS_IP_SLOT_TEMP_3 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_3 4
# elif CHAOS_IP_SLOT_TEMP_3 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_3 5
# elif CHAOS_IP_SLOT_TEMP_3 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_3 6
# elif CHAOS_IP_SLOT_TEMP_3 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_3 7
# elif CHAOS_IP_SLOT_TEMP_3 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_3 8
# elif CHAOS_IP_SLOT_TEMP_3 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_3 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_2 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_2 0
# elif CHAOS_IP_SLOT_TEMP_2 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_2 1
# elif CHAOS_IP_SLOT_TEMP_2 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_2 2
# elif CHAOS_IP_SLOT_TEMP_2 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_2 3
# elif CHAOS_IP_SLOT_TEMP_2 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_2 4
# elif CHAOS_IP_SLOT_TEMP_2 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_2 5
# elif CHAOS_IP_SLOT_TEMP_2 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_2 6
# elif CHAOS_IP_SLOT_TEMP_2 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_2 7
# elif CHAOS_IP_SLOT_TEMP_2 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_2 8
# elif CHAOS_IP_SLOT_TEMP_2 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_2 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_1 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_1 0
# elif CHAOS_IP_SLOT_TEMP_1 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_1 1
# elif CHAOS_IP_SLOT_TEMP_1 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_1 2
# elif CHAOS_IP_SLOT_TEMP_1 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_1 3
# elif CHAOS_IP_SLOT_TEMP_1 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_1 4
# elif CHAOS_IP_SLOT_TEMP_1 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_1 5
# elif CHAOS_IP_SLOT_TEMP_1 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_1 6
# elif CHAOS_IP_SLOT_TEMP_1 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_1 7
# elif CHAOS_IP_SLOT_TEMP_1 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_1 8
# elif CHAOS_IP_SLOT_TEMP_1 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_1 9
# endif
#
# if CHAOS_IP_SLOT_TEMP_0 == 0
#    define CHAOS_IP_SLOT_1_DIGIT_0 0
# elif CHAOS_IP_SLOT_TEMP_0 == 1
#    define CHAOS_IP_SLOT_1_DIGIT_0 1
# elif CHAOS_IP_SLOT_TEMP_0 == 2
#    define CHAOS_IP_SLOT_1_DIGIT_0 2
# elif CHAOS_IP_SLOT_TEMP_0 == 3
#    define CHAOS_IP_SLOT_1_DIGIT_0 3
# elif CHAOS_IP_SLOT_TEMP_0 == 4
#    define CHAOS_IP_SLOT_1_DIGIT_0 4
# elif CHAOS_IP_SLOT_TEMP_0 == 5
#    define CHAOS_IP_SLOT_1_DIGIT_0 5
# elif CHAOS_IP_SLOT_TEMP_0 == 6
#    define CHAOS_IP_SLOT_1_DIGIT_0 6
# elif CHAOS_IP_SLOT_TEMP_0 == 7
#    define CHAOS_IP_SLOT_1_DIGIT_0 7
# elif CHAOS_IP_SLOT_TEMP_0 == 8
#    define CHAOS_IP_SLOT_1_DIGIT_0 8
# elif CHAOS_IP_SLOT_TEMP_0 == 9
#    define CHAOS_IP_SLOT_1_DIGIT_0 9
# endif
#
# if CHAOS_PP_VARIADICS
#    if CHAOS_IP_SLOT_1_DIGIT_9
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_9, CHAOS_IP_SLOT_1_DIGIT_8, CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_8
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_8, CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_7
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_6
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_5
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_4
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_3
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_2
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_1
#        define CHAOS_IP_SLOT_1() CHAOS_PP_VARIADIC_CAT(CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    else
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_1_DIGIT_0
#    endif
# else
#    if CHAOS_IP_SLOT_1_DIGIT_9
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(10)(CHAOS_IP_SLOT_1_DIGIT_9, CHAOS_IP_SLOT_1_DIGIT_8, CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_8
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(9)(CHAOS_IP_SLOT_1_DIGIT_8, CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_7
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(8)(CHAOS_IP_SLOT_1_DIGIT_7, CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_6
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(7)(CHAOS_IP_SLOT_1_DIGIT_6, CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_5
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(6)(CHAOS_IP_SLOT_1_DIGIT_5, CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_4
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(5)(CHAOS_IP_SLOT_1_DIGIT_4, CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_3
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(4)(CHAOS_IP_SLOT_1_DIGIT_3, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_2
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(3)(CHAOS_IP_SLOT_1_DIGIT_2, CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    elif CHAOS_IP_SLOT_1_DIGIT_1
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_CC(2)(CHAOS_IP_SLOT_1_DIGIT_1, CHAOS_IP_SLOT_1_DIGIT_0)
#    else
#        define CHAOS_IP_SLOT_1() CHAOS_IP_SLOT_1_DIGIT_0
#    endif
# endif
